-- CREATE DATABASE customer_behavior;
USE customer_behavior;

-- 1. What is the total revenue generated by male VS female Customers ? 
SELECT 
gender,
SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;

-- 2. Which customer discount but purchase more than the purchase amount? 
SELECT 
customer_id,
purchase_amount 
FROM customers
WHERE
discount_applied = 'Yes' AND
 purchase_amount > (SELECT AVG(purchase_amount)
FROM customers);

-- 3. Which are the top five product highest average review rating ? 
SELECT
item_purchased,
ROUND(AVG(review_rating),2) AS Average_Review_Rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4. Compare the average purchase amount Between Standard and Express Shipping ?  
SELECT 
shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customers
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- 5. Do subscribe customer Spend more ? Compare average spend Of total revenue Between subscriber and non subscriber . 
SELECT 
subscription_status,
ROUND(COUNT(customer_id),2) AS Total_Customers,
ROUND(AVG(purchase_amount),2) AS Average_Spend,
ROUND(SUM(purchase_amount),2) AS Revenue
FROM customers
GROUP BY subscription_status 
ORDER BY Revenue DESC;

-- 6.Which five products have the highest percentage Of purchase with discount applied ? 
SELECT
item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) * 100 AS purchased_percentage
FROM customers
GROUP BY item_purchased
ORDER BY purchased_percentage DESC
LIMIT 5;

-- 7.Segment customers into New, Returning And loyal based On their total number Of their previous purchases,
-- And show the count of each segment ? 
WITH customer_type AS (
	SELECT
	customer_id,
	previous_purchases,
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyel'
		END AS customer_segment 
	FROM customers)
SELECT
customer_segment,
COUNT(*) FROM customer_type
GROUP BY customer_segment;


-- 8.What are the top 3 Most purchased Product Within Each category ?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- 9.Our customer who are repeat buyers [ previous purchase more than 5  ]  Also likely to subscribe ?  
SELECT 
subscription_status,
COUNT(customer_id) AS repeat_customers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_customers DESC;

-- 10.What is the age contribution of Each group ?
SELECT
age_group,
SUM(purchase_amount) AS Revenue
FROM customers
GROUP BY age_group 
ORDER BY Revenue DESC;

















